## CSC311 – Machine Learning 2019 – GROUP 26 HAND SHAPE RECOGNITION 

### Phase 2 Testing and Results Generation

##### SOME INITIALISING CODE

In [31]:
import numpy as np
from IPython.display import display,HTML

np.set_printoptions(suppress=True)

from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))

### Reading Data

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
from PIL import Image
from scipy import ndimage
import train_svm
import log_reg
import train_nn

data = np.genfromtxt('group26_test.csv',delimiter=",", dtype="int32")

In [33]:
#Set X and y for test
X_test = data[:,:-1]
y_test = data[:,12288]

# Scaling X
X_test_scaled = (X_test / 255)

### Support Vector Machine Technique

#### Retrieving Model

In [34]:
from sklearn.svm import SVC

svm_model = train_svm.getmodel()

### Results Generation

#### Overall Accuracy

In [35]:
y_pred = svm_model.predict(X_test_scaled)
svm_predictions = y_pred
accuracy = svm_model.score(X_test_scaled,y_test)

In [36]:
accuracy = accuracy * 100

print("The overall accuracy is "+ str(accuracy))

The overall accuracy is 91.33333333333333


### Confusion Matrix

In [37]:
from sklearn.metrics import classification_report, confusion_matrix
svm_matrix = confusion_matrix(y_test,y_pred)
print(svm_matrix) 


[[45  0  0  1  1  3]
 [ 0 48  2  0  0  0]
 [ 0  3 44  2  0  1]
 [ 0  0  2 45  2  1]
 [ 0  0  0  3 46  1]
 [ 0  0  0  4  0 46]]


### Testing Metrics

In [38]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       1.00      0.90      0.95        50
           1       0.94      0.96      0.95        50
           2       0.92      0.88      0.90        50
           3       0.82      0.90      0.86        50
           4       0.94      0.92      0.93        50
           5       0.88      0.92      0.90        50

   micro avg       0.91      0.91      0.91       300
   macro avg       0.92      0.91      0.91       300
weighted avg       0.92      0.91      0.91       300



### Per-Class Accuracy

In [39]:
for i in range(5):
    print("Class "+ str(i) + " has " +  str(svm_matrix[i][i]/50*100) +" % Accuracy")

Class 0 has 90.0 % Accuracy
Class 1 has 96.0 % Accuracy
Class 2 has 88.0 % Accuracy
Class 3 has 90.0 % Accuracy
Class 4 has 92.0 % Accuracy


### Logistic Regression Technique

#### Retrieving Model

In [40]:
from sklearn.linear_model import LogisticRegression

logistic_model = log_reg.getmodel()

### Results Generation

#### Overall Accuracy 

In [70]:
y_pred = logistic_model.predict(X_test_scaled)
receive = y_pred
accuracy = logistic_model.score(X_test_scaled,y_test)

In [71]:
accuracy = accuracy * 100

print("The overall accuracy is "+ str(accuracy))

The overall accuracy is 80.33333333333333


### Confusion Matrix

In [72]:
logistic_matrix = confusion_matrix(y_test,y_pred)
print(logistic_matrix)

[[42  2  0  2  3  1]
 [ 0 46  4  0  0  0]
 [ 5  1 41  1  1  1]
 [ 3  1  0 38  7  1]
 [ 2  0  1  3 39  5]
 [ 2  0  0  4  9 35]]


### Testing Metrics

In [73]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.78      0.84      0.81        50
           1       0.92      0.92      0.92        50
           2       0.89      0.82      0.85        50
           3       0.79      0.76      0.78        50
           4       0.66      0.78      0.72        50
           5       0.81      0.70      0.75        50

   micro avg       0.80      0.80      0.80       300
   macro avg       0.81      0.80      0.80       300
weighted avg       0.81      0.80      0.80       300



### Per-Class Accuracy

In [74]:
for i in range(5):
    print("Class "+ str(i) + " has " +  str(logistic_matrix[i][i]/50*100) +" % Accuracy")

Class 0 has 84.0 % Accuracy
Class 1 has 92.0 % Accuracy
Class 2 has 82.0 % Accuracy
Class 3 has 76.0 % Accuracy
Class 4 has 78.0 % Accuracy


### Neural Networks Technique

#### Retrieving Model

In [75]:
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor

nn_model = train_nn.getmodel()

### Results Generation

#### Overall Accuracy 

In [76]:
y_pred = nn_model.predict(X_test_scaled)
neural_predictions = y_pred
accuracy = nn_model.score(X_test_scaled,y_test)

In [77]:
accuracy = accuracy * 100

print("The overall accuracy is "+ str(accuracy))

The overall accuracy is 37.333333333333336


### Confusion Matrix

In [78]:
neural_matrix = confusion_matrix(y_test,y_pred)
print(neural_matrix)

[[16  2  0  0 32  0]
 [ 0 29  1  0 20  0]
 [ 0  4  7  0 39  0]
 [ 2  0  0 10 38  0]
 [ 0  0  0  0 50  0]
 [ 0  0  0  0 50  0]]


### Testing Metrics

In [79]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.89      0.32      0.47        50
           1       0.83      0.58      0.68        50
           2       0.88      0.14      0.24        50
           3       1.00      0.20      0.33        50
           4       0.22      1.00      0.36        50
           5       0.00      0.00      0.00        50

   micro avg       0.37      0.37      0.37       300
   macro avg       0.64      0.37      0.35       300
weighted avg       0.64      0.37      0.35       300



/home/mansa/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Per-Class Accuracy

In [80]:
for i in range(5):
    print("Class "+ str(i) + " has " +  str(neural_matrix[i][i]/50*100) +" % Accuracy")

Class 0 has 32.0 % Accuracy
Class 1 has 57.99999999999999 % Accuracy
Class 2 has 14.000000000000002 % Accuracy
Class 3 has 20.0 % Accuracy
Class 4 has 100.0 % Accuracy


### Additional Relevant Analysis

#### Storing predictions of models for demo

In [81]:
def getsvm():
    return svm_predictions

def getlog():
    return receive

def getneural():
    return neural_predictions
    